import translations from '../content/zh.json';
const zh:Record<string,string>=translations;
export let language:'en'|'zh'=document.documentElement.lang==='zh'?'zh':'en';
export let theme:'dark'|'light'=document.documentElement.dataset.theme==='light'?'light':'dark';
let baseTitle=document.title;
export function setPageTitle(value:string){baseTitle=value;document.title=baseTitle.split(' · ').map(t).join(' · ');}
export function t(value:string):string{if(language==='en')return value;if(/^Live WebGPU · [\d,]+ individual stars$/.test(value))return '实时 WebGPU · '+value.match(/[\d,]+/)![0]+' 颗独立星点';if(value.startsWith('WebGPU error:'))return 'WebGPU 错误：'+value.slice(13);if(value.startsWith('Live GPU sky · '))return '实时 GPU 星空 · '+value.slice(15).replace(' computed samples',' 个计算采样');if(value.endsWith(' GPU render'))return (zh[value.slice(0,-11)]??value.slice(0,-11))+' GPU 渲染图';return zh[value]??(value.startsWith('GPU error:')?'GPU 错误：'+value.slice(10):value.startsWith('Interactive ')?'交互演示：'+(zh[value.slice(12)]??value.slice(12)):value);}
const reverse=Object.fromEntries(Object.entries(zh).map(([en,cn])=>[cn,en]));
function english(value:string){const key=value.trim();const original=reverse[key]??(/^实时 WebGPU · [\d,]+ 颗独立星点$/.test(key)?'Live WebGPU · '+key.match(/[\d,]+/)![0]+' individual stars':key.startsWith('实时 GPU 星空 · ')?'Live GPU sky · '+key.slice('实时 GPU 星空 · '.length).replace(' 个计算采样',' computed samples'):key);return value.replace(key,original);}
const originals=new WeakMap<Text,{original:string,rendered:string}>();
export function applyLanguage(root:ParentNode=document.body){document.documentElement.lang=language;document.title=baseTitle.split(' · ').map(t).join(' · ');const walker=document.createTreeWalker(root as Node,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){const text=node as Text;if(text.parentElement?.closest('pre,code,script,style,[data-no-translate]'))continue;const current=text.textContent??'';let saved=originals.get(text);if(!saved||current!==saved.rendered)saved={original:english(current),rendered:current};const key=saved.original.trim();if(!key)continue;const replacement=t(key);saved.rendered=saved.original.replace(key,replacement);if(current!==saved.rendered)text.textContent=saved.rendered;originals.set(text,saved);}
 for(const el of root.querySelectorAll<HTMLElement>('[aria-label],[placeholder],[title],img[alt]'))for(const attr of ['aria-label','placeholder','title','alt']){if(!el.hasAttribute(attr))continue;const key='data-original-'+attr;const original=el.getAttribute(key)??el.getAttribute(attr)!;el.setAttribute(key,original);el.setAttribute(attr,t(original));}
 const languageButton=document.querySelector('#language-toggle');if(languageButton){languageButton.textContent=language==='zh'?'EN':'中文';languageButton.setAttribute('aria-label',language==='zh'?'Switch to English':'切换到中文');languageButton.setAttribute('data-no-translate','');}
}
export let themeProgress=theme==='light'?1:0;
const colorPairs:Record<string,[string,string]>={page:['#03050c','#f4f6fa'],ink:['#ededf4','#182337'],muted:['#9398aa','#5e6b80'],line:['#272b39','#d6dde7'],panel:['#080b13','#ffffff'],soft:['#121724','#e9edf4']};
function paintTheme(value:number){themeProgress=value;const root=document.documentElement;root.style.setProperty('--day',String(value));for(const [name,pair] of Object.entries(colorPairs)){const rgb=pair.map(hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)));root.style.setProperty('--'+name,`rgb(${rgb[0].map((x,i)=>Math.round(x+(rgb[1][i]-x)*value)).join(',')})`);}document.dispatchEvent(new CustomEvent('themeprogress',{detail:value}));}
export function initPreferences(onTheme:(theme:'dark'|'light')=>void){
 document.querySelector('#language-toggle')?.addEventListener('click',()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('wgpu-language',language);}catch{}applyLanguage();document.dispatchEvent(new Event('languagechange'));});
 let animation=0,last=0,target=themeProgress;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const animate=(now:number)=>{animation=0;const dt=last?Math.min(.08,(now-last)/1000):1/60;last=now;const next=themeProgress+(target-themeProgress)*(1-Math.exp(-3.8*dt));paintTheme(Math.abs(next-target)<.001?target:next);if(themeProgress!==target)animation=requestAnimationFrame(animate);};
 const updateTheme=()=>{document.documentElement.dataset.theme=theme;updateThemeAssets();const b=document.querySelector('#theme-toggle');if(b){b.textContent=theme==='dark'?'☼':'☾';b.setAttribute('aria-pressed',String(theme==='light'));b.setAttribute('data-original-aria-label',theme==='dark'?'Switch to light theme':'Switch to dark theme');b.setAttribute('aria-label',t(theme==='dark'?'Switch to light theme':'Switch to dark theme'));}document.querySelector('meta[name=theme-color]')?.setAttribute('content',theme==='dark'?'#03050c':'#f4f6fa');};
 document.querySelector('#theme-toggle')?.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';target=theme==='light'?1:0;try{localStorage.setItem('wgpu-theme',theme);}catch{}updateTheme();onTheme(theme);if(reduced){if(animation)cancelAnimationFrame(animation);animation=0;paintTheme(target);}else if(!animation){last=0;animation=requestAnimationFrame(animate);}});
 const font=document.querySelector<HTMLSelectElement>('#font-size');let scale='1';try{scale=localStorage.getItem('wgpu-font-scale')||'1';}catch{}if(!['1','1.1','1.25','1.5'].includes(scale))scale='1';document.documentElement.style.setProperty('--reading-scale',scale);if(font){font.value=scale;font.addEventListener('change',()=>{document.documentElement.style.setProperty('--reading-scale',font.value);try{localStorage.setItem('wgpu-font-scale',font.value);}catch{}});}
 updateTheme();paintTheme(themeProgress);applyLanguage();for(const type of ['click','input','languagechange'])document.addEventListener(type,()=>setTimeout(applyLanguage,0));
}

export function updateThemeAssets(root:ParentNode=document.body){for(const img of root.querySelectorAll<HTMLImageElement>('img[data-light]')){img.src=img.dataset.dark!;if(!img.parentElement?.querySelector('.theme-light-preview')){const light=img.cloneNode(false) as HTMLImageElement;light.removeAttribute('data-light');light.removeAttribute('data-dark');light.src=img.dataset.light!;light.classList.add('theme-light-preview');light.alt='';light.setAttribute('aria-hidden','true');img.after(light);}}}
