import { mountGravitationalLens } from './gravitational-lens';
import { GpuContext, Buffer, elementKernel } from 'wgpu-kit';
import type { DemoController } from './examples';
export const LABS = [
 {"id":"gravitational-lens","title":"Gravitational lens","description":"Drag a point-mass lens across a galaxy atlas. Watch a spiral stretch into arcs and split into multiple images.","tags":"thin-lens equation · inverse ray mapping","param":"Relative lens mass","min":0.25,"max":2.5,"value":1,"hint":"Drag to move the lens; arrow keys make fine adjustments. Switch Lens off to compare the exact same sky. Enable the source grid to see the geometry bend.","explanation":"Each pixel traces an observed image angle back to the source atlas with the point-mass thin-lens equation: β = θ − θE²(θ − lens)/|θ − lens|². The blue spiral becomes arcs near alignment; off-axis galaxies produce a larger image and an inverted secondary image. Relative mass scales θE² at fixed distances. This dimensionless, weak-field, geometric-optics approximation uses a procedural source atlas and a tiny numerical floor at the point singularity. The crosshair marks the lens, and the constellation and grid are visual guides. It does not model strong-field black-hole optics or an accretion disk. Both views keep identical exposure and a fixed source atlas."},
 {id:'volumetric-nebula',title:'Volumetric nebula',description:'Fly through layered clouds of interstellar color, integrated along a camera ray.',tags:'volume integration · noise',param:'Cloud density',min:.25,max:2.5,value:1,hint:'Move the pointer to change the viewing direction. Density changes how light accumulates.',explanation:'Each invocation marches through a three-dimensional fractal-noise density field. Front-to-back emission and absorption accumulate into a translucent nebula. The density slider changes optical depth rather than simply adjusting brightness.'},
 {id:'aurora-curtains',title:'Aurora curtains',description:'Folded ribbons of atmospheric light drape above a quiet horizon.',tags:'ray integration · atmosphere',param:'Curtain folds',min:.3,max:2.5,value:1,hint:'Move to steer the curtain. Change the fold frequency and pause the light.',explanation:'A camera ray integrates many thin emissive layers. A warped ridge field defines the auroral curtain, while altitude controls its green-to-magenta emission. This is an artistic atmospheric model.'},
 {id:'ocean-caustics',title:'Ocean caustics',description:'Refracted light gathers into an intricate lattice under a moving water surface.',tags:'surface derivatives · caustics',param:'Wave sharpness',min:.3,max:2,value:1,hint:'Move to change the light direction. Sharpness controls the concentrated ridges.',explanation:'Several directional waves form a surface slope field. Its local derivative compresses light into bright caustic ridges. The result is a real-time approximation of underwater light concentration, not a full optical ray trace.'},
 {id:'mandelbulb',title:'Mandelbulb explorer',description:'A rotating, self-similar three-dimensional world carved by a distance estimator.',tags:'3D fractal · raymarch',param:'Fractal power',min:3,max:10,value:8,hint:'Move horizontally to orbit the fractal. Power changes the geometry itself.',explanation:'A spherical-coordinate power map iterates a three-dimensional escape-time fractal. Its distance estimate drives sphere tracing; nearby samples estimate a surface normal for lighting. Iteration and step counts are bounded for interactive rendering.'},
 {id:'newton-basins',title:'Newton basins',description:'Three roots divide the complex plane into infinitely folded regions of attraction.',tags:'complex arithmetic · convergence',param:'Zoom',min:.5,max:4,value:1,hint:'Move to pan the complex plane. Zoom into the borders between the three roots.',explanation:'Each pixel applies Newton’s method to z³ − 1. The converged root selects its color; the number of iterations controls the banding. The intricate boundaries arise from convergence, not from a painted texture.'},
 {id:'voronoi-glass',title:'Voronoi stained glass',description:'Moving sites tessellate the plane into luminous, irregular panes.',tags:'nearest neighbor · tessellation',param:'Cell density',min:3,max:14,value:7,hint:'Move the pointer to change the light spot. Density changes the number of cells.',explanation:'A 3 × 3 search finds the nearest and second-nearest animated feature points. Their distance gap draws the leaded seams, while a hash assigns each pane a stable jewel color.'},
 {id:'diffraction-aperture',title:'Diffraction aperture',description:'Coherent waves from a slit array interfere into colored diffraction bands.',tags:'complex amplitude · interference',param:'Slit count',min:2,max:12,value:5,hint:'Move to alter slit spacing. The control changes how many coherent apertures contribute.',explanation:'The kernel sums complex amplitudes from a finite, equally spaced slit array for three wavelengths, then squares their magnitudes to obtain intensity. A single-slit sinc envelope modulates the result. It is a dimensionless far-field model, not a calibrated optical instrument.'},
 {id:'curl-flow',title:'Curl-flow streamlines',description:'Fine threads trace a divergence-free flow field like ink stretched through water.',tags:'curl field · integration',param:'Flow complexity',min:.4,max:2.2,value:1,hint:'Move the pointer to bend the flow. Complexity changes the vector field, not chemical reactions.',explanation:'Finite differences of a scalar potential define a two-dimensional curl field. Every pixel integrates a short path through it and accumulates thin dye-like marks. This is streamline integration, distinct from the reaction-diffusion example.'},
 {id:'contour-terrain',title:'Contour terrain',description:'A miniature world rises from a height field, etched with survey-like elevation lines.',tags:'height field · raymarch',param:'Relief',min:.3,max:2,value:1,hint:'Move horizontally to orbit. Relief changes the landscape’s actual elevation.',explanation:'A camera ray intersects a multi-octave height field. Finite differences estimate normals, while quantized elevation draws contour lines. The relief slider changes both the silhouette and the shadowed surface.'},
] as const;
const common=`
fn hash(p:vec2f)->f32{return fract(sin(dot(p,vec2f(127.1,311.7)))*43758.5453);}
fn noise(p:vec2f)->f32{let i=floor(p);let f=fract(p);let u=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2f(1,0)),u.x),mix(hash(i+vec2f(0,1)),hash(i+vec2f(1,1)),u.x),u.y);}
fn fbm(p0:vec2f)->f32{var p=p0;var s=0.0;var a=0.5;for(var j=0;j<5;j++){s+=a*noise(p);p=mat2x2f(1.62,1.17,-1.17,1.62)*p+3.71;a*=0.5;}return s;}
fn palette(t:f32)->vec3f{return 0.5+0.5*cos(6.283185*(vec3f(.1,.35,.6)+t));}
fn stars(p:vec2f)->vec3f{let q=p*130.0;let cell=floor(q);let f=fract(q)-0.5;let h=hash(cell);let r=length(f-vec2f(hash(cell+1.7),hash(cell+8.2))*.35);let b=pow(max(0.0,1.0-r*8.0),6.0)*step(.965,h);return mix(vec3f(.55,.7,1),vec3f(1,.72,.4),hash(cell+4.1))*b*2.5;}
`;
const bodies:Record<string,string>={
'volumetric-nebula':`var trans=1.0;var col=vec3f(0);for(var k=0;k<28;k++){let z=f32(k)*.13;let q=p*1.3+pointer*.22+vec2f(z*.18,sin(z+time*.1)*.22);let n=fbm(q*2.2+vec2f(z*.8,time*.035));let d=max(0.0,n-.40)*amount*.23;let light=mix(vec3f(.22,.075,.65),vec3f(.04,.75,.8),clamp(z/3.6,0.0,1.0));col+=trans*d*light*2.6;trans*=exp(-d*1.5);}rgb=col+stars(p)*trans;`,
'aurora-curtains':`var col=vec3f(.009,.018,.05);for(var k=0;k<32;k++){let z=f32(k)/32.0;let x=p.x*(1.0+z*.8)+pointer.x*.2;let ridge=sin(x*4.0*amount+time*.18+z*2.8)*.14+sin(x*9.0+z*3.0)*.05;let y=p.y+.18-z*.43;let curtain=exp(-abs(y-ridge)*22.0);let filament=pow(noise(vec2f(x*80.0,z*1.7+time*.05)),2.0);col+=curtain*filament*mix(vec3f(.02,.8,.39),vec3f(.58,.1,.6),z)*.14;}rgb=col+stars(p)*smoothstep(-.35,.5,-p.y);`,
'ocean-caustics':`let q=p*3.0+pointer*.2;var v=vec2f(0);for(var k=0;k<5;k++){let a=f32(k)*2.399;let d=vec2f(cos(a),sin(a));let phase=dot(q,d)*(2.7+f32(k)*.8)+time*(.65+f32(k)*.12);v+=d*sin(phase)*.4;}let s=sin((q.x+v.x)*8.0)*sin((q.y+v.y)*8.0);let ridges=pow(1.0-abs(s),12.0/max(.2,amount));let deep=.5+.5*fbm(q);rgb=vec3f(.006,.06,.10)+vec3f(.05,.63,.71)*ridges*(.6+deep)+vec3f(.01,.1,.15)*deep;`,
'mandelbulb':`let yaw=time*.12+pointer.x*1.8;let ro=vec3f(sin(yaw)*2.65,.35+pointer.y*.6,cos(yaw)*2.65);let ww=normalize(-ro);let uu=normalize(cross(ww,vec3f(0,1,0)));let vv=cross(uu,ww);let rd=normalize(ww+p.x*uu-p.y*vv);var t=0.0;var hit=false;var pos=ro;var steps=0.0;for(var k=0;k<64;k++){pos=ro+rd*t;let d=bulb(pos,amount);if(d<.003){hit=true;break;}t+=max(d,.002);steps=f32(k);if(t>7.0){break;}}rgb=vec3f(.008,.012,.025)+vec3f(.025,.04,.07)*max(0.0,1.0-length(p));if(hit){let e=.004;let n=normalize(vec3f(bulb(pos+vec3f(e,0,0),amount)-bulb(pos-vec3f(e,0,0),amount),bulb(pos+vec3f(0,e,0),amount)-bulb(pos-vec3f(0,e,0),amount),bulb(pos+vec3f(0,0,e),amount)-bulb(pos-vec3f(0,0,e),amount)));let lit=max(0.0,dot(n,normalize(vec3f(-.6,1,1))));rgb=mix(vec3f(.24,.48,.62),vec3f(.94,.63,.3),clamp(length(pos)*.7,0.0,1.0))*(.3+lit*.9)*(1.0-steps/100.0)+pow(max(0.0,dot(reflect(rd,n),normalize(vec3f(-.6,1,1)))),16.0)*.5;}`,
'newton-basins':`var z=p*2.0/max(.3,amount)+pointer*.5;var iterations=0.0;for(var k=0;k<36;k++){let z2=cmul(z,z);let f=cmul(z2,z)-vec2f(1,0);let d=z2*3.0;z-=cdiv(f,d);iterations=f32(k);if(length(f)<.0001){break;}}let d0=distance(z,vec2f(1,0));let d1=distance(z,vec2f(-.5,.8660254));let d2=distance(z,vec2f(-.5,-.8660254));var base=vec3f(.91,.35,.14);if(d1<d0&&d1<d2){base=vec3f(.1,.63,.77);}if(d2<d0&&d2<d1){base=vec3f(.6,.25,.87);}rgb=base*(.18+.82*exp(-iterations*.065))*(.7+.3*cos(iterations*1.2));`,
'voronoi-glass':`let q=p*amount;let cell=floor(q);let f=fract(q);var first=9.0;var second=9.0;var ident=0.0;for(var y=-1;y<=1;y++){for(var x=-1;x<=1;x++){let off=vec2f(f32(x),f32f(y));let h=vec2f(hash(cell+off),hash(cell+off+7.1));let site=off+.5+.36*sin(6.28*h+time*.22);let dist=length(site-f);if(dist<first){second=first;first=dist;ident=h.x;}else{second=min(second,dist);}}}let seam=smoothstep(.015,.065,second-first);let glow=.5+.5*exp(-length(p-pointer*.5)*1.2);rgb=palette(ident)*seam*glow+vec3f(.012)*(1.0-seam);`,
'diffraction-aperture':`let x=p.x*18.0;let y=p.y;let n=u32(clamp(round(amount),2.0,12.0));let spacing=1.1+pointer.x*.65;var channels=vec3f(0);for(var channel=0u;channel<3u;channel++){let wavelength=.62-f32(channel)*.1;var amplitude=vec2f(0);for(var k=0u;k<12u;k++){if(k>=n){break;}let phase=(f32(k)-f32(n-1u)*.5)*x*spacing/wavelength;amplitude+=vec2f(cos(phase),sin(phase));}let arg=x*.15/wavelength;let envelope=select(1.0,sin(arg)/arg,abs(arg)>.0001);channels[channel]=dot(amplitude,amplitude)/f32(n*n)*envelope*envelope;}rgb=pow(max(channels,vec3f(0)),vec3f(.45))*exp(-y*y*7.0)+vec3f(.006,.008,.015);`,
'curl-flow':`var q=p*3.0;var accum=0.0;for(var k=0;k<20;k++){let e=.025;let a=potential(q+vec2f(e,0),time,amount);let b=potential(q-vec2f(e,0),time,amount);let c=potential(q+vec2f(0,e),time,amount);let d=potential(q-vec2f(0,e),time,amount);let velocity=vec2f(c-d,b-a)/(2.0*e)+pointer*.17;q+=velocity*.023;let stripe=pow(.5+.5*sin(q.x*48.0+q.y*17.0),18.0);accum+=stripe/20.0;}rgb=vec3f(.01,.022,.035)+mix(vec3f(.05,.55,.65),vec3f(1,.53,.22),clamp(p.x*.4+.5,0.0,1.0))*accum*2.1;`,
'contour-terrain':`let yaw=pointer.x*1.8+time*.045;let ro=vec3f(sin(yaw)*3.0,2.0,cos(yaw)*3.0);let lookAt=vec3f(0,.2,0);let ww=normalize(lookAt-ro);let uu=normalize(cross(ww,vec3f(0,1,0)));let vv=cross(uu,ww);let rd=normalize(ww+p.x*uu-p.y*vv);var travel=0.0;var hit=false;var pos=ro;for(var k=0;k<72;k++){pos=ro+rd*travel;let d=pos.y-terrain(pos.xz,amount);if(d<.005){hit=true;break;}travel+=max(.025,d*.35);if(travel>9.0){break;}}rgb=mix(vec3f(.025,.04,.065),vec3f(.13,.18,.24),clamp(p.y+.4,0.0,1.0));if(hit){let e=.012;let h=terrain(pos.xz,amount);let n=normalize(vec3f(terrain(pos.xz-vec2f(e,0),amount)-terrain(pos.xz+vec2f(e,0),amount),2.0*e,terrain(pos.xz-vec2f(0,e),amount)-terrain(pos.xz+vec2f(0,e),amount)));let lit=.45+.85*max(0.0,dot(n,normalize(vec3f(-1,1,.5))));let contour=smoothstep(.04,.12,abs(fract(h*17.0)-.5));rgb=mix(vec3f(.07,.28,.25),vec3f(.8,.68,.4),clamp(h/amount,0.0,1.0))*lit*(.5+.5*contour);rgb=mix(rgb,vec3f(.04,.08,.1),1.0-exp(-travel*.055));}`,
};
bodies['voronoi-glass']=bodies['voronoi-glass'].replace('f32f(y)','f32(y)');
const helpers:Record<string,string>={
'mandelbulb':`fn bulb(p:vec3f,power:f32)->f32{var z=p;var dr=1.0;var r=0.0;for(var j=0;j<8;j++){r=length(z);if(r>2.0){break;}let safe=max(r,.0001);let theta=acos(clamp(z.z/safe,-1.0,1.0));let phi=atan2(z.y,z.x);dr=pow(safe,power-1.0)*power*dr+1.0;let zr=pow(safe,power);z=zr*vec3f(sin(theta*power)*cos(phi*power),sin(theta*power)*sin(phi*power),cos(theta*power))+p;}return .5*log(max(r,1.001))*r/dr;}`,
'newton-basins':`fn cmul(a:vec2f,b:vec2f)->vec2f{return vec2f(a.x*b.x-a.y*b.y,a.x*b.y+a.y*b.x);}fn cdiv(a:vec2f,b:vec2f)->vec2f{return vec2f(dot(a,b),a.y*b.x-a.x*b.y)/max(dot(b,b),.00001);}`,
'curl-flow':`fn potential(p:vec2f,t:f32,a:f32)->f32{return sin(p.x*a+t*.2)*cos(p.y*a-t*.13)+.45*sin(p.x*2.1+p.y*1.7+t*.1)+.25*cos(p.y*3.7-p.x*1.3);}`,
'contour-terrain':`fn terrain(p:vec2f,a:f32)->f32{return (fbm(p*1.05)-.23)*a*.9;}`,
};
export const LAB_SHADERS=Object.fromEntries(LABS.filter(l=>l.id!=='gravitational-lens').map(l=>[l.id,`${common}\n${helpers[l.id]??''}\nfn userFn(idx:u32,size:u32,time:f32,pointer:vec2f,amount:f32,aspect:f32,light:f32){let uv=(vec2f(f32(idx%size),f32(idx/size))+.5)/f32(size);let p=(uv-.5)*vec2f(2.0*aspect,2.0);var rgb=vec3f(0);${bodies[l.id]}\nif(light>.5){rgb=mix(vec3f(.88,.91,.94),rgb,.76);}color[idx]=vec4f(clamp(rgb,vec3f(0),vec3f(1)),1);}`]));
export const LAB_SOURCES=Object.fromEntries(LABS.filter(l=>l.id!=='gravitational-lens').map(l=>[l.id,`import { Buffer, elementKernel } from 'wgpu-kit';\n\nconst color = await Buffer.create('vec4f', size * size);\nconst shader = elementKernel({\n  state: { color: 'vec4f' },\n  uniforms: { size: 'u32', time: 'f32', pointer: 'vec2f', amount: 'f32', aspect: 'f32', light: 'f32' },\n  code: \`${LAB_SHADERS[l.id]}\`,\n});\nawait shader.run({ color }, { size, time: 0, pointer: { x: 0, y: 0 }, amount: ${l.value}, aspect: 1.5, light: 0 });\n// The complete module includes a native WebGPU render pass.\n// Download labs.ts for the full canvas runtime and cleanup.`]));
const view=`@group(0) @binding(0) var<storage,read> pixels:array<vec4f>;@group(0) @binding(1) var<uniform> screen:vec4u;struct Out{@builtin(position) p:vec4f,@location(0) uv:vec2f};@vertex fn vs(@builtin(vertex_index)i:u32)->Out{var p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));var o:Out;o.p=vec4f(p[i],0,1);o.uv=p[i]*vec2f(.5,-.5)+.5;return o;}@fragment fn fs(v:Out)->@location(0) vec4f{let xy=min(vec2u(clamp(v.uv,vec2f(0),vec2f(.99999))*f32(screen.x)),vec2u(screen.x-1u));return pixels[xy.y*screen.x+xy.x];}`;
export async function mountLab(id:string,canvas:HTMLCanvasElement,onStatus:(s:string)=>void,options:{reducedMotion?:boolean,theme?:string}={}):Promise<DemoController>{
 if(id==='gravitational-lens')return mountGravitationalLens(canvas,onStatus,options);
 const spec=LABS.find(l=>l.id===id);if(!spec)throw Error('Unknown lab');const ctx=await GpuContext.get(),device=ctx.device,size=384;const surface=canvas.getContext('webgpu');if(!surface)throw Error('A WebGPU canvas is unavailable.');const format=navigator.gpu.getPreferredCanvasFormat();surface.configure({device,format,alphaMode:'opaque'});
 const color=await Buffer.create('vec4f',size*size);const screen=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(screen,0,new Uint32Array([size,0,0,0]));
 const module=device.createShaderModule({code:view});const pipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format}]},primitive:{topology:'triangle-list'}});const group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:color.gpuBuffer}},{binding:1,resource:{buffer:screen}}]});
 const kernel=elementKernel({name:id,state:{color:'vec4f'},uniforms:{size:'u32',time:'f32',pointer:'vec2f',amount:'f32',aspect:'f32',light:'f32'},code:LAB_SHADERS[id]});await kernel.prepare();let dead=false,paused=!!options.reducedMotion,dirty=true,visible=true,frame=0,time=0,last=0,amount:number=spec.value,pointer={x:0,y:0},light=options.theme==='light'?1:0;
 const draw=(now:number)=>{if(dead)return;frame=requestAnimationFrame(draw);if(!visible||document.hidden||paused&&!dirty)return;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!paused)time+=dt;dirty=false;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));try{const encoder=device.createCommandEncoder();kernel.encode(encoder,{color},{size,time,pointer,amount,aspect:canvas.width/canvas.height,light});const pass=encoder.beginRenderPass({colorAttachments:[{view:surface.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:1}}]});pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.draw(3);pass.end();device.queue.submit([encoder.finish()]);kernel.endSubmit();}catch(e){paused=true;onStatus('GPU error: '+String(e));}};
 const move=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)/r.width*2-1,y:(e.clientY-r.top)/r.height*2-1};dirty=true;};const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')pointer.x-=.05;else if(e.key==='ArrowRight')pointer.x+=.05;else if(e.key==='ArrowUp')pointer.y-=.05;else if(e.key==='ArrowDown')pointer.y+=.05;else return;e.preventDefault();dirty=true;};canvas.addEventListener('pointermove',move);canvas.addEventListener('keydown',key);canvas.style.touchAction='pan-y';const observer=new IntersectionObserver(es=>{visible=es[0].isIntersecting;last=0;dirty=true;});observer.observe(canvas);const resizeObserver=new ResizeObserver(()=>{dirty=true;last=0;});resizeObserver.observe(canvas);const error=(e:GPUUncapturedErrorEvent)=>{paused=true;onStatus('GPU error: '+e.error.message);};device.addEventListener('uncapturederror',error);frame=requestAnimationFrame(draw);onStatus('Live WebGPU · wgpu-kit 2.0.1');return{destroy(){dead=true;cancelAnimationFrame(frame);observer.disconnect();resizeObserver.disconnect();canvas.removeEventListener('pointermove',move);canvas.removeEventListener('keydown',key);device.removeEventListener('uncapturederror',error);kernel.destroy();color.destroy();screen.destroy();surface.unconfigure();},setPaused(v){paused=v;last=0;dirty=true;},reset(){time=0;pointer={x:0,y:0};amount=spec.value;dirty=true;},setParameter(key,value){if(key==='amount')amount=value;if(key==='theme')light=value;dirty=true;}};
}
